// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VVPU1RouteHarness.h for the primary calling header

#ifndef VERILATED_VVPU1ROUTEHARNESS___024ROOT_H_
#define VERILATED_VVPU1ROUTEHARNESS___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"
class VVPU1RouteHarness_QuantActCore;


class VVPU1RouteHarness__Syms;

class alignas(VL_CACHE_LINE_BYTES) VVPU1RouteHarness___024root final : public VerilatedModule {
  public:
    // CELLS
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_0;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_1;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_2;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_3;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_4;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_5;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_6;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_7;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_8;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_9;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_10;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_11;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_12;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_13;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_14;
    VVPU1RouteHarness_QuantActCore* __PVT__VPU1RouteHarness__DOT__qa__DOT__cores_15;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_tpu_valid,0,0);
        VL_IN8(io_ub_0,7,0);
        VL_IN8(io_ub_1,7,0);
        VL_IN8(io_ub_2,7,0);
        VL_IN8(io_ub_3,7,0);
        VL_IN8(io_ub_4,7,0);
        VL_IN8(io_ub_5,7,0);
        VL_IN8(io_ub_6,7,0);
        VL_IN8(io_ub_7,7,0);
        VL_IN8(io_ub_8,7,0);
        VL_IN8(io_ub_9,7,0);
        VL_IN8(io_ub_10,7,0);
        VL_IN8(io_ub_11,7,0);
        VL_IN8(io_ub_12,7,0);
        VL_IN8(io_ub_13,7,0);
        VL_IN8(io_ub_14,7,0);
        VL_IN8(io_ub_15,7,0);
        VL_IN8(io_wb_0,7,0);
        VL_IN8(io_wb_1,7,0);
        VL_IN8(io_wb_2,7,0);
        VL_IN8(io_wb_3,7,0);
        VL_IN8(io_wb_4,7,0);
        VL_IN8(io_wb_5,7,0);
        VL_IN8(io_wb_6,7,0);
        VL_IN8(io_wb_7,7,0);
        VL_IN8(io_wb_8,7,0);
        VL_IN8(io_wb_9,7,0);
        VL_IN8(io_wb_10,7,0);
        VL_IN8(io_wb_11,7,0);
        VL_IN8(io_wb_12,7,0);
        VL_IN8(io_wb_13,7,0);
        VL_IN8(io_wb_14,7,0);
        VL_IN8(io_wb_15,7,0);
        VL_IN8(io_ub_valid,0,0);
        VL_IN8(io_wb_valid,0,0);
        VL_IN8(io_vb_read_data_0,7,0);
        VL_IN8(io_vb_read_data_1,7,0);
        VL_IN8(io_vb_read_data_2,7,0);
        VL_IN8(io_vb_read_data_3,7,0);
        VL_IN8(io_vb_read_data_4,7,0);
        VL_IN8(io_vb_read_data_5,7,0);
        VL_IN8(io_vb_read_data_6,7,0);
        VL_IN8(io_vb_read_data_7,7,0);
        VL_IN8(io_vb_read_data_8,7,0);
        VL_IN8(io_vb_read_data_9,7,0);
        VL_IN8(io_vb_read_data_10,7,0);
        VL_IN8(io_vb_read_data_11,7,0);
        VL_IN8(io_vb_read_data_12,7,0);
        VL_IN8(io_vb_read_data_13,7,0);
        VL_IN8(io_vb_read_data_14,7,0);
        VL_IN8(io_vb_read_data_15,7,0);
        VL_OUT8(io_vb_read_req,0,0);
        VL_IN8(io_input_mode,0,0);
        VL_IN8(io_output_route,1,0);
        VL_IN8(io_alu_mode,1,0);
        VL_IN8(io_out_shift,4,0);
        VL_IN8(io_act_mask,1,0);
        VL_IN8(io_fusion_second,0,0);
        VL_IN8(io_stall,0,0);
        VL_IN8(io_lut_wr_en,0,0);
        VL_IN8(io_lut_wr_addr,5,0);
        VL_IN8(io_lut_wr_data_0,7,0);
    };
    struct {
        VL_IN8(io_lut_wr_data_1,7,0);
        VL_IN8(io_lut_wr_data_2,7,0);
        VL_IN8(io_lut_wr_data_3,7,0);
        VL_IN8(io_lut_wr_data_4,7,0);
        VL_IN8(io_lut_wr_data_5,7,0);
        VL_IN8(io_lut_wr_data_6,7,0);
        VL_IN8(io_lut_wr_data_7,7,0);
        VL_IN8(io_lut_wr_data_8,7,0);
        VL_IN8(io_lut_wr_data_9,7,0);
        VL_IN8(io_lut_wr_data_10,7,0);
        VL_IN8(io_lut_wr_data_11,7,0);
        VL_IN8(io_lut_wr_data_12,7,0);
        VL_IN8(io_lut_wr_data_13,7,0);
        VL_IN8(io_lut_wr_data_14,7,0);
        VL_IN8(io_lut_wr_data_15,7,0);
        VL_OUT8(io_result_0,7,0);
        VL_OUT8(io_result_1,7,0);
        VL_OUT8(io_result_2,7,0);
        VL_OUT8(io_result_3,7,0);
        VL_OUT8(io_result_4,7,0);
        VL_OUT8(io_result_5,7,0);
        VL_OUT8(io_result_6,7,0);
        VL_OUT8(io_result_7,7,0);
        VL_OUT8(io_result_8,7,0);
        VL_OUT8(io_result_9,7,0);
        VL_OUT8(io_result_10,7,0);
        VL_OUT8(io_result_11,7,0);
        VL_OUT8(io_result_12,7,0);
        VL_OUT8(io_result_13,7,0);
        VL_OUT8(io_result_14,7,0);
        VL_OUT8(io_result_15,7,0);
        VL_OUT8(io_vb_valid,0,0);
        VL_OUT8(io_vpu2_valid,0,0);
        VL_OUT8(io_compute_valid,0,0);
        VL_OUT8(io_result_valid,0,0);
        VL_OUT8(io_drained,0,0);
        VL_OUT8(io_control_alert,0,0);
        VL_OUT8(io_sync_alert,0,0);
        VL_OUT8(io_qparam_req,0,0);
        CData/*0:0*/ VPU1RouteHarness__DOT__busy;
        CData/*0:0*/ VPU1RouteHarness__DOT__savedMode;
        CData/*1:0*/ VPU1RouteHarness__DOT__savedRoute;
        CData/*1:0*/ VPU1RouteHarness__DOT__route;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_0;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_1;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_2;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_3;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_4;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_5;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_6;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_7;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_8;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_9;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_10;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_11;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_12;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_13;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_14;
        CData/*7:0*/ VPU1RouteHarness__DOT__vbResponse_15;
        CData/*0:0*/ VPU1RouteHarness__DOT____VdfgTmp_ha4a0e0fa__0;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_0_io_input_mode;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_0_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_1_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_2_io_in_valid;
    };
    struct {
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_3_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_4_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_5_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_6_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_7_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_8_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_9_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_10_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_11_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_12_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_13_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_14_io_in_valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__qa__DOT__cores_15_io_in_valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s1B;
        CData/*4:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s1Shift;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s1Direct;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s1Valid;
        CData/*4:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s2Shift;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s2Direct;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s3Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s3Direct;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT___io_out_tpu_valid_T;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__s1B;
        CData/*1:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__s1Mode;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__s2Valid;
    };
    struct {
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__s3Valid;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__s1A;
        CData/*7:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__s1B;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__s1Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__s2Valid;
        CData/*0:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__s3Valid;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactContinue;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_0__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_1__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_2__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_3__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__io_out_tpu_r;
    };
    struct {
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_4__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_5__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_6__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_7__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_8__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_9__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_10__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_11__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_12__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_13__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_14__DOT__io_out_direct_r;
        SData/*8:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT___result_T_1;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__s2Result;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__shifted;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__io_out_tpu_r;
        SData/*15:0*/ VPU1RouteHarness__DOT__alu__DOT__cores_15__DOT__io_out_direct_r;
        VL_IN(io_tpu_0,31,0);
        VL_IN(io_tpu_1,31,0);
        VL_IN(io_tpu_2,31,0);
        VL_IN(io_tpu_3,31,0);
        VL_IN(io_tpu_4,31,0);
        VL_IN(io_tpu_5,31,0);
        VL_IN(io_tpu_6,31,0);
        VL_IN(io_tpu_7,31,0);
    };
    struct {
        VL_IN(io_tpu_8,31,0);
        VL_IN(io_tpu_9,31,0);
        VL_IN(io_tpu_10,31,0);
        VL_IN(io_tpu_11,31,0);
        VL_IN(io_tpu_12,31,0);
        VL_IN(io_tpu_13,31,0);
        VL_IN(io_tpu_14,31,0);
        VL_IN(io_tpu_15,31,0);
        VL_IN(io_matrix_param,31,0);
        IData/*31:0*/ __VactIterCount;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    VVPU1RouteHarness__Syms* const vlSymsp;

    // CONSTRUCTORS
    VVPU1RouteHarness___024root(VVPU1RouteHarness__Syms* symsp, const char* v__name);
    ~VVPU1RouteHarness___024root();
    VL_UNCOPYABLE(VVPU1RouteHarness___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(uint32_t* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp);
};


#endif  // guard
