// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VCOMPUTEUNITE2EHARNESS__SYMS_H_
#define VERILATED_VCOMPUTEUNITE2EHARNESS__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "VComputeUnitE2EHarness.h"

// INCLUDE MODULE CLASSES
#include "VComputeUnitE2EHarness___024root.h"
#include "VComputeUnitE2EHarness_TransposerUnit.h"
#include "VComputeUnitE2EHarness_Accum_buffer.h"
#include "VComputeUnitE2EHarness_QuantActCore.h"
#include "VComputeUnitE2EHarness_Universal_Wide_LUT_16.h"
#include "VComputeUnitE2EHarness_RopePairCore.h"

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)VComputeUnitE2EHarness__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    VComputeUnitE2EHarness* const __Vm_modelp;
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    VComputeUnitE2EHarness___024root TOP;
    VComputeUnitE2EHarness_TransposerUnit TOP__ComputeUnitE2EHarness__DOT__outTransposer__DOT__ping;
    VComputeUnitE2EHarness_TransposerUnit TOP__ComputeUnitE2EHarness__DOT__outTransposer__DOT__pong;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_0;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_1;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_10;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_11;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_12;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_13;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_14;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_15;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_2;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_3;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_4;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_5;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_6;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_7;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_8;
    VComputeUnitE2EHarness_Accum_buffer TOP__ComputeUnitE2EHarness__DOT__tpu__DOT__accumulator__DOT__buffers_9;
    VComputeUnitE2EHarness_TransposerUnit TOP__ComputeUnitE2EHarness__DOT__ubTransposer__DOT__ping;
    VComputeUnitE2EHarness_TransposerUnit TOP__ComputeUnitE2EHarness__DOT__ubTransposer__DOT__pong;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_0;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_1;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_10;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_11;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_12;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_13;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_14;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_15;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_2;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_3;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_4;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_5;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_6;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_7;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_8;
    VComputeUnitE2EHarness_QuantActCore TOP__ComputeUnitE2EHarness__DOT__vpu1__DOT__quant__DOT__cores_9;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_0;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_1;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_10;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_11;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_12;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_13;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_14;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_15;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_2;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_3;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_4;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_5;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_6;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_7;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_8;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__correctionExpLuts_9;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_0;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_1;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_10;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_11;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_12;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_13;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_14;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_15;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_2;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_3;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_4;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_5;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_6;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_7;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_8;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__phase2ExpLuts_9;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_0;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_1;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_10;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_11;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_12;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_13;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_14;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_15;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_2;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_3;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_4;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_5;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_6;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_7;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_8;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__scaleLuts_9;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_0;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_1;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_10;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_11;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_12;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_13;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_14;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_15;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_2;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_3;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_4;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_5;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_6;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_7;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_8;
    VComputeUnitE2EHarness_Universal_Wide_LUT_16 TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__norm__DOT__streamExpLuts_9;
    VComputeUnitE2EHarness_RopePairCore TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__rope__DOT__pairs_0;
    VComputeUnitE2EHarness_RopePairCore TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__rope__DOT__pairs_1;
    VComputeUnitE2EHarness_RopePairCore TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__rope__DOT__pairs_2;
    VComputeUnitE2EHarness_RopePairCore TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__rope__DOT__pairs_3;
    VComputeUnitE2EHarness_RopePairCore TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__rope__DOT__pairs_4;
    VComputeUnitE2EHarness_RopePairCore TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__rope__DOT__pairs_5;
    VComputeUnitE2EHarness_RopePairCore TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__rope__DOT__pairs_6;
    VComputeUnitE2EHarness_RopePairCore TOP__ComputeUnitE2EHarness__DOT__vpu2__DOT__rope__DOT__pairs_7;
    VComputeUnitE2EHarness_TransposerUnit TOP__ComputeUnitE2EHarness__DOT__wbTransposer__DOT__ping;
    VComputeUnitE2EHarness_TransposerUnit TOP__ComputeUnitE2EHarness__DOT__wbTransposer__DOT__pong;

    // CONSTRUCTORS
    VComputeUnitE2EHarness__Syms(VerilatedContext* contextp, const char* namep, VComputeUnitE2EHarness* modelp);
    ~VComputeUnitE2EHarness__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
